//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_playArea_DrawOrMove;
        
        private static SteamVR_Action_Boolean p_playArea_SnapToPoint;
        
        private static SteamVR_Action_Boolean p_playArea_AdjustFloorToController;
        
        private static SteamVR_Action_Vector2 p_playArea_MoveFloor;
        
        private static SteamVR_Action_Pose p_playArea_Pose;
        
        private static SteamVR_Action_Boolean p_playArea_HeadsetOnHead;
        
        private static SteamVR_Action_Boolean p_playArea_UISelect;
        
        private static SteamVR_Action_Boolean p_playArea_DeletePoint;
        
        private static SteamVR_Action_Vibration p_playArea_Haptic;
        
        public static SteamVR_Action_Boolean playArea_DrawOrMove
        {
            get
            {
                return SteamVR_Actions.p_playArea_DrawOrMove.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean playArea_SnapToPoint
        {
            get
            {
                return SteamVR_Actions.p_playArea_SnapToPoint.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean playArea_AdjustFloorToController
        {
            get
            {
                return SteamVR_Actions.p_playArea_AdjustFloorToController.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 playArea_MoveFloor
        {
            get
            {
                return SteamVR_Actions.p_playArea_MoveFloor.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Pose playArea_Pose
        {
            get
            {
                return SteamVR_Actions.p_playArea_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean playArea_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_playArea_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean playArea_UISelect
        {
            get
            {
                return SteamVR_Actions.p_playArea_UISelect.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean playArea_DeletePoint
        {
            get
            {
                return SteamVR_Actions.p_playArea_DeletePoint.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration playArea_Haptic
        {
            get
            {
                return SteamVR_Actions.p_playArea_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.playArea_DrawOrMove,
                    SteamVR_Actions.playArea_SnapToPoint,
                    SteamVR_Actions.playArea_AdjustFloorToController,
                    SteamVR_Actions.playArea_MoveFloor,
                    SteamVR_Actions.playArea_Pose,
                    SteamVR_Actions.playArea_HeadsetOnHead,
                    SteamVR_Actions.playArea_UISelect,
                    SteamVR_Actions.playArea_DeletePoint,
                    SteamVR_Actions.playArea_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.playArea_DrawOrMove,
                    SteamVR_Actions.playArea_SnapToPoint,
                    SteamVR_Actions.playArea_AdjustFloorToController,
                    SteamVR_Actions.playArea_MoveFloor,
                    SteamVR_Actions.playArea_Pose,
                    SteamVR_Actions.playArea_HeadsetOnHead,
                    SteamVR_Actions.playArea_UISelect,
                    SteamVR_Actions.playArea_DeletePoint};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.playArea_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.playArea_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.playArea_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.playArea_DrawOrMove,
                    SteamVR_Actions.playArea_SnapToPoint,
                    SteamVR_Actions.playArea_AdjustFloorToController,
                    SteamVR_Actions.playArea_HeadsetOnHead,
                    SteamVR_Actions.playArea_UISelect,
                    SteamVR_Actions.playArea_DeletePoint};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.playArea_MoveFloor};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.playArea_DrawOrMove,
                    SteamVR_Actions.playArea_SnapToPoint,
                    SteamVR_Actions.playArea_AdjustFloorToController,
                    SteamVR_Actions.playArea_MoveFloor,
                    SteamVR_Actions.playArea_HeadsetOnHead,
                    SteamVR_Actions.playArea_UISelect,
                    SteamVR_Actions.playArea_DeletePoint};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_playArea_DrawOrMove = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PlayArea/in/DrawOrMove")));
            SteamVR_Actions.p_playArea_SnapToPoint = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PlayArea/in/SnapToPoint")));
            SteamVR_Actions.p_playArea_AdjustFloorToController = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PlayArea/in/AdjustFloorToController")));
            SteamVR_Actions.p_playArea_MoveFloor = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/PlayArea/in/MoveFloor")));
            SteamVR_Actions.p_playArea_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/PlayArea/in/Pose")));
            SteamVR_Actions.p_playArea_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PlayArea/in/HeadsetOnHead")));
            SteamVR_Actions.p_playArea_UISelect = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PlayArea/in/UISelect")));
            SteamVR_Actions.p_playArea_DeletePoint = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PlayArea/in/DeletePoint")));
            SteamVR_Actions.p_playArea_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/PlayArea/out/Haptic")));
        }
    }
}
