//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_PlayArea : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean DrawOrMove
        {
            get
            {
                return SteamVR_Actions.playArea_DrawOrMove;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapToPoint
        {
            get
            {
                return SteamVR_Actions.playArea_SnapToPoint;
            }
        }
        
        public virtual SteamVR_Action_Boolean AdjustFloorToController
        {
            get
            {
                return SteamVR_Actions.playArea_AdjustFloorToController;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MoveFloor
        {
            get
            {
                return SteamVR_Actions.playArea_MoveFloor;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.playArea_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.playArea_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean UISelect
        {
            get
            {
                return SteamVR_Actions.playArea_UISelect;
            }
        }
        
        public virtual SteamVR_Action_Boolean DeletePoint
        {
            get
            {
                return SteamVR_Actions.playArea_DeletePoint;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.playArea_Haptic;
            }
        }
    }
}
